### ISSUE TITLE
Multi-regional recombee setup missing

### ISSUE THREAD

**Issue by strizr** [kontent-ai/example-integration-recombee#9]
### Brief bug description

Recombee added multi-regional support to their product - it is currently being initialized via their recombee-api-client (https://www.npmjs.com/package/recombee-api-client). The integration is linking an older npm version and the RecombeeClient wrapper (https://github.com/kontent-ai/integration-example-recombee/blob/main/src/functions/model/recombee-client.ts)  does not support this new parameter hence not allowing users to select the correct server to connect to.

**Comment by JiriLojda** [comment]
Fixed by #10
